### PR TITLE
feat: remove maven transfert progress when sets version

### PR DESCRIPTION
**Pull request by djeanprost**

### CODE REVIEW

**Comment by djeanprost** [comment]
links to #36

**Comment by simonseyock** [comment]
This only works for maven 3.6.1 or greater. Do you think this might be a problem?

**Comment by djeanprost** [comment]
Hello @simonseyock when [this](https://github.com/terrestris/maven-semantic-release/issues/16#issuecomment-1682730452) changed was applied, it wasn't a problem. I think it's still not.

maven 3.6.1 was released in 2019 as release note [mentions](https://maven.apache.org/docs/history.html#maven-3-6-x-and-before) it, and it is deprecated, so I really think we shouldn't care about that.

**Review by simonseyock — APPROVED** [review]

**Comment by simonseyock** [comment]
Allright, thanks for the changes!

**Pull request merged**
